from __future__ import annotations

from .click_keyframes import (
    _add_silent_gap_keyframes,
    _cluster_click_keyframe_events,
    _nearest_click_marker,
    build_click_keyframe_plan,
    build_click_keyframe_visual_signatures,
    load_click_keyframe_events,
    load_click_markers,
    select_click_keyframes,
    select_click_keyframes_with_stats,
)
from .ffmpeg_io import extract_preview_frame, probe_video, resolve_ffmpeg, resolve_ffprobe
from .models import (
    ClickKeyframeConfig,
    ClickKeyframeEstimate,
    ClickKeyframeEvent,
    ClickKeyframeResult,
    ClickKeyframeSelection,
    ClickMarker,
    ClickVisualSignature,
    CropRegion,
    DenseRange,
    FramePlanEntry,
    FrameSamplerConfig,
    FrameSamplerEstimate,
    FrameSamplerResult,
    ProgressCallback,
    VideoInfo,
)
from .planner import build_frame_plan, estimate_sampling
from .presets import (
    CLICK_SUMMARY_POLICY_ID,
    CLICK_SUMMARY_SILENT_INTERVAL_SECONDS,
    build_click_summary_config,
    click_summary_policy,
)
from .renderer import _compose_sheet, _crop_and_resize, _draw_click_marker, _prepare_frame_image
from .service import (
    default_output_dir,
    estimate_click_keyframe_sampling,
    generate_click_keyframe_sheets,
    run_frame_export,
    sample_video_to_sheets,
)
from .timecode import format_timecode, parse_timecode

__all__ = [
    "ClickKeyframeConfig",
    "CLICK_SUMMARY_POLICY_ID",
    "CLICK_SUMMARY_SILENT_INTERVAL_SECONDS",
    "ClickKeyframeEstimate",
    "ClickKeyframeEvent",
    "ClickKeyframeResult",
    "ClickKeyframeSelection",
    "ClickMarker",
    "ClickVisualSignature",
    "CropRegion",
    "DenseRange",
    "FramePlanEntry",
    "FrameSamplerConfig",
    "FrameSamplerEstimate",
    "FrameSamplerResult",
    "ProgressCallback",
    "VideoInfo",
    "_add_silent_gap_keyframes",
    "_cluster_click_keyframe_events",
    "_compose_sheet",
    "_crop_and_resize",
    "_draw_click_marker",
    "_nearest_click_marker",
    "_prepare_frame_image",
    "build_click_keyframe_plan",
    "build_click_summary_config",
    "build_click_keyframe_visual_signatures",
    "build_frame_plan",
    "click_summary_policy",
    "default_output_dir",
    "estimate_sampling",
    "estimate_click_keyframe_sampling",
    "extract_preview_frame",
    "format_timecode",
    "generate_click_keyframe_sheets",
    "load_click_keyframe_events",
    "load_click_markers",
    "parse_timecode",
    "probe_video",
    "resolve_ffmpeg",
    "resolve_ffprobe",
    "run_frame_export",
    "sample_video_to_sheets",
    "select_click_keyframes",
    "select_click_keyframes_with_stats",
]
